# this manually operated workflow deploys code from the develop branch to the testing environment

name: Deploy to test environment

on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  build_and_deploy_to_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Deployment Scripts
      run: |
        python deployment/deploy.py --to_env test
        
